/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FactraInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createInvoice"
      | "fundInvoice"
      | "getInvoice"
      | "getInvoiceCount"
      | "invoiceCounter"
      | "invoices"
      | "markAsPaid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "InvoiceCreated" | "InvoiceFunded" | "InvoicePaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fundInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoiceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invoices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsPaid",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInvoice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvoiceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invoiceCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invoices", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markAsPaid", data: BytesLike): Result;
}

export namespace InvoiceCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    issuer: AddressLike,
    amount: BigNumberish,
    dueDate: BigNumberish,
    businessName: string,
    sector: string,
    rating: BigNumberish,
    discountRate: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    issuer: string,
    amount: bigint,
    dueDate: bigint,
    businessName: string,
    sector: string,
    rating: bigint,
    discountRate: bigint
  ];
  export interface OutputObject {
    id: bigint;
    issuer: string;
    amount: bigint;
    dueDate: bigint;
    businessName: string;
    sector: string;
    rating: bigint;
    discountRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceFundedEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoicePaidEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Factra extends BaseContract {
  connect(runner?: ContractRunner | null): Factra;
  waitForDeployment(): Promise<this>;

  interface: FactraInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createInvoice: TypedContractMethod<
    [
      amount: BigNumberish,
      dueDate: BigNumberish,
      businessName: string,
      sector: string,
      rating: BigNumberish,
      discountRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  fundInvoice: TypedContractMethod<[id: BigNumberish], [void], "payable">;

  getInvoice: TypedContractMethod<
    [id: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ]
    ],
    "view"
  >;

  getInvoiceCount: TypedContractMethod<[], [bigint], "view">;

  invoiceCounter: TypedContractMethod<[], [bigint], "view">;

  invoices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        issuer: string;
        buyer: string;
        amount: bigint;
        dueDate: bigint;
        status: bigint;
        businessName: string;
        sector: string;
        rating: bigint;
        discountRate: bigint;
      }
    ],
    "view"
  >;

  markAsPaid: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      dueDate: BigNumberish,
      businessName: string,
      sector: string,
      rating: BigNumberish,
      discountRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundInvoice"
  ): TypedContractMethod<[id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getInvoice"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvoiceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoiceCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        issuer: string;
        buyer: string;
        amount: bigint;
        dueDate: bigint;
        status: bigint;
        businessName: string;
        sector: string;
        rating: bigint;
        discountRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markAsPaid"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "InvoiceCreated"
  ): TypedContractEvent<
    InvoiceCreatedEvent.InputTuple,
    InvoiceCreatedEvent.OutputTuple,
    InvoiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceFunded"
  ): TypedContractEvent<
    InvoiceFundedEvent.InputTuple,
    InvoiceFundedEvent.OutputTuple,
    InvoiceFundedEvent.OutputObject
  >;
  getEvent(
    key: "InvoicePaid"
  ): TypedContractEvent<
    InvoicePaidEvent.InputTuple,
    InvoicePaidEvent.OutputTuple,
    InvoicePaidEvent.OutputObject
  >;

  filters: {
    "InvoiceCreated(uint256,address,uint256,uint256,string,string,uint8,uint8)": TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;
    InvoiceCreated: TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;

    "InvoiceFunded(uint256,address,uint256)": TypedContractEvent<
      InvoiceFundedEvent.InputTuple,
      InvoiceFundedEvent.OutputTuple,
      InvoiceFundedEvent.OutputObject
    >;
    InvoiceFunded: TypedContractEvent<
      InvoiceFundedEvent.InputTuple,
      InvoiceFundedEvent.OutputTuple,
      InvoiceFundedEvent.OutputObject
    >;

    "InvoicePaid(uint256)": TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;
    InvoicePaid: TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;
  };
}
