/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Factra } from "./Factra";
export * as factories from "./factories";
export { Factra__factory } from "./factories/Factra__factory";
